{
 "title": "URL Shortener Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Shortened Links",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "urls_shortened_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of URL Creations & Redirections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "rate(urls_shortened_total[1m])", "legendFormat": "Creations" },
    { "expr": "rate(redirects_total[1m])", "legendFormat": "Redirections" }
   ]
  },
  {
   "title": "95th Percentile Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Rate of 404 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(failed_lookups_total[1m])", "legendFormat": "404 Errors" }
   ]
  }
 ]
}